

UIItems:
    -
        Name: "Root"
        Parent: "None"
        Type: "Canvas"
        
        Dimentions:
            Size: [1300, 700]
            Pos: [290, 150]

        Rules:
            AttachCorner: "TOPLEFT"
            Rigid: [0, 0]
            MinSize: [30, 30]
