
UIItems:
    -
        Name: "Root"
        Parent: "__NONE__"
        Size: [2000, 2000]
        Pos: [0, 0]
        Rigid: [false, false]
        MinSize: [30, 30]
        AttachCorner: "TOPLEFT"

        Template:
            Using: "Group"
            With:
                OwnBuff: false
                Frame: true
                Pallete: [In: 429273033, Out: 428937489]
                Thickness: [In: 3, Out: 2]

    -
        Name: "Window"
        Parent: "Root"
        Size: [1300, 700]
        Pos: [290, 150]
        Rigid: [false, false]
        MinSize: [10, 10]
        AttachCorner: "TOPLEFT"

        Template:
            Using: "Group"
            With:
                OwnBuff: true
                Frame: true
                Pallete: [In: 429273033, Out: 428937489]
                Thickness: [In: 3, Out: 2]
    -
        Name: "Window2"
        Parent: "Root"
        Size: [50, 50]
        Pos: [100, 100]
        Rigid: [false, false]
        MinSize: [10, 10]
        AttachCorner: "TOPLEFT"

        Template:
            Using: "Group"
            With:
                OwnBuff: true
                Frame: true
                Pallete: [In: 429273033, Out: 428937489]
                Thickness: [In: 3, Out: 2]

    -
        Name: "Buttons"
        Parent: "Window"
        Size: [400, 200]
        Pos: [100, 100]
        Rigid: [false, false]
        MinSize: [10, 10]
        AttachCorner: "TOPLEFT"

        Template:
            Using: "Group"
            With:
                OwnBuff: false
                Frame: true
                Pallete: [In: 429273033, Out: 428937489]
                Thickness: [In: 3, Out: 2]

    -
        Name: "Move Item"
        Parent: "Buttons"
        Size: [40, 20]
        Pos: [20, 50]
        Rigid: [true, true]
        MinSize: [10, 10]
        AttachCorner: "TOPLEFT"

        Template:
            Using: "Button"
            With:
                Operator: "Move Window"
                On: "PRESSED"
                Args: [Pressed: "NONE", Hold: "NONE", Released: "FINISH"]        
                Pallete: [In: 429273033, Out: 428937489, Hold: 429496729]

    -
        Name: "console"
        Parent: "Buttons"
        Size: [40, 20]
        Pos: [90, 50]
        Rigid: [true, true]
        MinSize: [10, 10]
        AttachCorner: "TOPLEFT"

        Template:
            Using: "Button"
            With:
                Operator: "Toggle Console"
                On: "RELEASED"
                Args: [Pressed: "NONE", Hold: "NONE", Released: "NONE"]        
                Pallete: [In: 429273033, Out: 428937489, Hold: 429496729]