name: Build Test

on: [push, pull_request]

jobs:
  Buld_Test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build
      uses: nicledomaS/cmake_build_action@v1.3
      with:
        submodule_update: ON
        run_tests: ON
        unit_test_build: -Dtest=ON
